default:
  cost_type: "points"
  commission_per_side: 0.0
  spread: 0.0
  slippage: 0.0
  contract_multiplier: 1.0
  currency: "USD"

instruments:
  NDX:
    cost_type: "points"
    commission_per_side: 1.0
    spread: 1.0
    slippage: 0.5
    contract_multiplier: 1.0
    venue: "generic"

  NDXm:
    cost_type: "points"
    commission_per_side: 0.5
    spread: 0.5
    slippage: 0.25
    contract_multiplier: 1.0
    venue: "generic"

  SP500:
    cost_type: "points"
    commission_per_side: 0.275
    spread: 0.65
    slippage: 0.25
    contract_multiplier: 10
    venue: "Darwinex"

  EURAUD:
    cost_type: "points"
    commission_per_side: 0.5
    spread: 0.5
    slippage: 0.25
    contract_multiplier: 1.0
    venue: "generic"
